name: Mac OS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Java ${{ matrix.java }} Maven Wrapper
    runs-on: macos-13
    strategy:
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Project Using Fabric8 Kuberenetes Client v6.3.1
        run: |
          cd fabric8-issue-2
          mvn clean install
          mvn exec:java -Dexec.mainClass=com.mycompany.app.App

